from __future__ import annotations

from typing import Any, Literal, Optional, Union

TrackKind = Literal["video", "audio", "other"]
OverlapPolicy = Literal["override", "push"]
InsertPolicy = Literal[
    "split_and_insert", "insert_before", "insert_after", "insert_before_or_after"
]

class MediaSource:
    def __init__(
        self,
        url: str,
        name: Optional[str] = None,
        media_start: Optional[float] = None,
        media_duration: Optional[float] = None,
        metadata_json: Optional[str] = None,
    ) -> None: ...
    def get_url(self) -> str: ...
    def set_url(self, value: str) -> None: ...
    def get_media_start(self) -> float: ...
    def set_media_start(self, value: float) -> None: ...
    def get_media_duration(self) -> Optional[float]: ...
    def set_media_duration(self, value: Optional[float]) -> None: ...
    def get_metadata_json(self) -> str: ...
    def set_metadata_json(self, value: str) -> None: ...
    def __str__(self) -> str: ...

class Clip:
    def __init__(
        self,
        duration: float,
        source: MediaSource,
        name: Optional[str] = None,
        id: Optional[str] = None,
    ) -> None: ...
    def get_name(self) -> Optional[str]: ...
    def set_name(self, value: Optional[str]) -> None: ...
    def get_duration(self) -> float: ...
    def set_duration(self, value: float) -> None: ...
    def get_source(self) -> MediaSource: ...
    def set_source(self, value: MediaSource) -> None: ...
    def get_id(self) -> Optional[str]: ...
    def set_id(self, value: Optional[str]) -> None: ...
    def get_metadata_json(self) -> str: ...
    def set_metadata_json(self, value: str) -> None: ...
    def __str__(self) -> str: ...

class Gap:
    def get_name(self) -> Optional[str]: ...
    def set_name(self, value: Optional[str]) -> None: ...
    def __init__(self, duration: float, id: Optional[str] = None) -> None: ...
    def get_duration(self) -> float: ...
    def set_duration(self, value: float) -> None: ...
    def get_id(self) -> Optional[str]: ...
    def set_id(self, value: Optional[str]) -> None: ...
    def get_metadata_json(self) -> str: ...
    def set_metadata_json(self, value: str) -> None: ...
    def __str__(self) -> str: ...

class Item:
    @staticmethod
    def from_clip(c: Clip) -> Item: ...
    @staticmethod
    def from_gap(g: Gap) -> Item: ...
    def is_clip(self) -> bool: ...
    def is_gap(self) -> bool: ...
    def duration(self) -> float: ...
    def set_duration(self, dur: float) -> None: ...
    def get_id(self) -> Optional[str]: ...
    def set_id(self, value: Optional[str]) -> None: ...
    def __str__(self) -> str: ...

class Track:
    def get_name(self) -> Optional[str]: ...
    def set_name(self) -> None: ...
    def __init__(
        self,
        kind: Optional[TrackKind] = None,
        id: Optional[str] = None,
        children: Optional[list[Item]] = None,
    ) -> None: ...
    @property
    def kind(self) -> TrackKind: ...
    @kind.setter
    def kind(self, value: TrackKind) -> None: ...
    def items(self) -> list[Item]: ...
    def get_items(self) -> list[Item]: ...
    def clear_items(self) -> None: ...
    def set_items(self, items: list[Item]) -> None: ...
    def sanitize(self) -> None: ...
    def split_at_time(self, time: float) -> None: ...
    def get_item_at_time(self, time: float) -> Optional[int]: ...
    def get_item_by_id(self, id: str) -> Optional[tuple[int, Item]]: ...
    def get_id(self) -> Optional[str]: ...
    def set_id(self, value: Optional[str]) -> None: ...
    def replace_item(self, index: int, item: Union[Item, Clip, Gap]) -> bool: ...
    def delete_clip(self, index: int, replace_with_gap: bool) -> bool: ...
    def resize_item(
        self,
        index: int,
        new_start_time: float,
        new_duration: float,
        overlap_policy: OverlapPolicy,
        clamp_to_media: bool,
    ) -> bool: ...
    def total_duration(self) -> float: ...
    def start_time_of_item(self, index: int) -> float: ...
    def get_metadata_json(self) -> str: ...
    def set_metadata_json(self, value: str) -> None: ...
    def __str__(self) -> str: ...

class Stack:
    def __init__(self, children: Optional[list[Track]] = None) -> None: ...
    def get_name(self) -> Optional[str]: ...
    def set_name(self, value: Optional[str]) -> None: ...
    def tracks(self) -> list[Track]: ...
    def children(self) -> list[Track]: ...
    def clear_children(self) -> None: ...
    def add_track(self, track: Track, insertion_index: int = -1) -> None: ...
    def delete_track(self, id: str) -> Optional[Track]: ...
    def set_tracks(self, tracks: list[Track]) -> None: ...
    def sanitize(self) -> None: ...
    def get_track_by_id(self, id: str) -> Optional[tuple[int, Track]]: ...
    def get_item(self, id: str) -> Optional[tuple[int, int, Item]]: ...
    def delete_item(
        self, id: str, replace_with_gap: bool
    ) -> Optional[tuple[int, Item]]: ...
    def insert_item_at_time(
        self,
        dest_track_index: int,
        dest_time: float,
        item: Union[Item, Clip, Gap],
        overlap_policy: OverlapPolicy,
        insert_policy: InsertPolicy,
    ) -> Optional[str]: ...
    def get_metadata_json(self) -> str: ...
    def set_metadata_json(self, value: str) -> None: ...
    def __str__(self) -> str: ...
    def insert_item_at_index(
        self,
        dest_track_id: str,
        dest_index: int,
        item: Union[Item, Clip, Gap],
        overlap_policy: OverlapPolicy,
    ) -> Optional[str]: ...
    def move_item_at_time(
        self,
        item_id: str,
        dest_track_id: str,
        dest_time: float,
        replace_with_gap: bool,
        overlap_policy: OverlapPolicy,
        insert_policy: InsertPolicy,
    ) -> bool: ...
    def move_item_at_index(
        self,
        item_id: str,
        dest_track_id: str,
        dest_index: int,
        replace_with_gap: bool,
        overlap_policy: OverlapPolicy,
        insert_policy: InsertPolicy,
    ) -> bool: ...

class Timeline:
    def __init__(self, tracks: Optional[Union[Stack, list[Track]]] = None) -> None: ...
    @staticmethod
    def parse_json(s: str) -> Timeline: ...
    def to_json(self) -> str: ...
    def validate(self) -> list[str]: ...
    def sanitize(self) -> None: ...
    def get_name(self) -> Optional[str]: ...
    def set_name(self, value: Optional[str]) -> None: ...
    def get_stack(self) -> Stack: ...
    def set_stack(self, stack: Stack) -> None: ...
    def add_track(self, track: Track, insertion_index: int = -1) -> None: ...
    def delete_track(self, id: str) -> Optional[Track]: ...
    def move_item(self, item_id: str, dest_track_id: str, dest_time: float) -> bool: ...
    def get_metadata_json(self) -> str: ...
    def set_metadata_json(self, value: str) -> None: ...
    def __str__(self) -> str: ...
