from __future__ import annotations

from typing import Any, Literal, Optional, Union

class TimeRange:
    def __init__(self, duration: float, start_time: float = 0.0) -> None: ...
    def get_duration(self) -> float: ...
    def set_duration(self, value: float) -> None: ...
    def get_start_time(self) -> float: ...
    def set_start_time(self, value: float) -> None: ...
    def __str__(self) -> str: ...

TrackKind = Literal["video", "audio", "other"]
OverlapPolicy = Literal["override", "push"]
InsertPolicy = Literal[
    "split_and_insert", "insert_before", "insert_after", "insert_before_or_after"
]

class MediaReference:
    def __init__(
        self,
        url: str,
        name: Optional[str] = None,
        media_start: Optional[float] = None,
        media_duration: Optional[float] = None,
        metadata_json: Optional[str] = None,
    ) -> None: ...
    @staticmethod
    def parse_json(s: str) -> MediaReference: ...
    def get_url(self) -> str: ...
    def set_url(self, value: str) -> None: ...
    def get_media_start(self) -> float: ...
    def set_media_start(self, value: float) -> None: ...
    def get_media_duration(self) -> Optional[float]: ...
    def set_media_duration(self, value: Optional[float]) -> None: ...
    def get_metadata_json(self) -> str: ...
    def set_metadata_json(self, value: str) -> None: ...
    def get_rich_text(self) -> Optional[str]: ...
    @staticmethod
    def create_rich_text_reference(title_html: str) -> MediaReference: ...
    def __str__(self) -> str: ...

class MediaReferencePosition:
    def __init__(
        self,
        x: float = 0.5,
        y: float = 0.5,
        rotation: float = 0.0,
        zoom_x: float = 1.0,
        zoom_y: float = 1.0,
    ) -> None: ...
    def get_x(self) -> float: ...
    def set_x(self, value: float) -> None: ...
    def get_y(self) -> float: ...
    def set_y(self, value: float) -> None: ...
    def get_rotation(self) -> float: ...
    def set_rotation(self, value: float) -> None: ...
    def get_zoom_x(self) -> float: ...
    def set_zoom_x(self, value: float) -> None: ...
    def get_zoom_y(self) -> float: ...
    def set_zoom_y(self, value: float) -> None: ...

class Clip:
    def __init__(
        self,
        duration: float,
        references: dict[str, MediaReference],
        active_key: Optional[str] = None,
        name: Optional[str] = None,
        id: Optional[str] = None,
    ) -> None: ...
    @staticmethod
    def parse_json(s: str) -> Clip: ...
    def to_json(self) -> str: ...
    def get_name(self) -> Optional[str]: ...
    def set_name(self, value: Optional[str]) -> None: ...
    def get_enabled(self) -> bool: ...
    def set_enabled(self, value: bool) -> None: ...
    def get_duration(self) -> float: ...
    def set_duration(self, value: float) -> None: ...
    def get_media_references(self) -> dict[str, MediaReference]: ...
    def set_media_references(self, value: dict[str, MediaReference]) -> None: ...
    def get_active_media_reference_key(self) -> Optional[str]: ...
    def set_active_media_reference_key(self, value: Optional[str]) -> None: ...
    def get_id(self) -> Optional[str]: ...
    def set_id(self, value: Optional[str]) -> None: ...
    def get_metadata_json(self) -> str: ...
    def set_metadata_json(self, value: str) -> None: ...
    def get_position(self) -> MediaReferencePosition: ...
    def set_position(self, position: MediaReferencePosition) -> None: ...
    def get_volume(self) -> float: ...
    def set_volume(self, volume: float) -> None: ...
    def get_effects(self) -> list[Effect]: ...
    def set_effects(self, value: list[Effect]) -> None: ...
    def __str__(self) -> str: ...

class Gap:
    def get_name(self) -> Optional[str]: ...
    def set_name(self, value: Optional[str]) -> None: ...
    def __init__(self, duration: float, id: Optional[str] = None) -> None: ...
    def get_duration(self) -> float: ...
    def set_duration(self, value: float) -> None: ...
    def get_id(self) -> Optional[str]: ...
    def set_id(self, value: Optional[str]) -> None: ...
    def get_metadata_json(self) -> str: ...
    def set_metadata_json(self, value: str) -> None: ...
    def __str__(self) -> str: ...

class Effect:
    def __init__(self, name: Optional[str] = None, effect_name: Optional[str] = None, metadata_json: Optional[str] = None) -> None: ...
    def get_name(self) -> Optional[str]: ...
    def set_name(self, value: Optional[str]) -> None: ...
    def get_effect_name(self) -> Optional[str]: ...
    def set_effect_name(self, value: Optional[str]) -> None: ...
    def get_metadata_json(self) -> str: ...
    def set_metadata_json(self, value: str) -> None: ...
    def __str__(self) -> str: ...

class Item:
    @staticmethod
    def from_clip(c: Clip) -> Item: ...
    @staticmethod
    def from_gap(g: Gap) -> Item: ...
    def is_clip(self) -> bool: ...
    def is_gap(self) -> bool: ...
    def duration(self) -> float: ...
    def set_duration(self, dur: float) -> None: ...
    def get_enabled(self) -> bool: ...
    def set_enabled(self, value: bool) -> None: ...
    def get_source_range(self) -> TimeRange: ...
    def set_source_range(self, value: TimeRange) -> None: ...
    def get_media_references(self) -> dict[str, MediaReference]: ...
    def set_media_references(self, value: dict[str, MediaReference]) -> None: ...
    def get_active_media_reference_key(self) -> Optional[str]: ...
    def set_active_media_reference_key(self, value: Optional[str]) -> None: ...
    def get_id(self) -> Optional[str]: ...
    def set_id(self, value: Optional[str]) -> None: ...
    def get_metadata_json(self) -> str: ...
    def set_metadata_json(self, value: str) -> None: ...
    def get_effects(self) -> list[Effect]: ...
    def set_effects(self, value: list[Effect]) -> None: ...
    def get_position(self) -> MediaReferencePosition: ...
    def set_position(self, position: MediaReferencePosition) -> None: ...
    def get_volume(self) -> float: ...
    def set_volume(self, volume: float) -> None: ...
    def __str__(self) -> str: ...

class Track:
    def get_name(self) -> Optional[str]: ...
    def set_name(self, value: Optional[str]) -> None: ...
    def __init__(
        self,
        kind: Optional[TrackKind] = None,
        id: Optional[str] = None,
        children: Optional[list[Item]] = None,
    ) -> None: ...
    def get_enabled(self) -> bool: ...
    def set_enabled(self, value: bool) -> None: ...
    @property
    def kind(self) -> TrackKind: ...
    @kind.setter
    def kind(self, value: TrackKind) -> None: ...
    def items(self) -> list[Item]: ...
    def get_items(self) -> list[Item]: ...
    def timeline_ids(self) -> list[str]: ...
    def clear_items(self) -> None: ...
    def set_items(self, items: list[Item]) -> None: ...
    def sanitize(self) -> None: ...
    def split_at_time(self, time: float) -> None: ...
    def get_item_at_time(self, time: float) -> Optional[int]: ...
    def get_item_by_id(self, id: str) -> Optional[tuple[int, Item]]: ...
    def get_id(self) -> Optional[str]: ...
    def set_id(self, value: Optional[str]) -> None: ...
    def replace_item(self, index: int, item: Union[Item, Clip, Gap]) -> bool: ...
    def delete_clip(self, index: int, replace_with_gap: bool) -> bool: ...
    def resize_item(
        self,
        index: int,
        new_start_time: float,
        new_duration: float,
        overlap_policy: OverlapPolicy,
        clamp_to_media: bool,
    ) -> bool: ...
    def total_duration(self) -> float: ...
    def start_time_of_item(self, index: int) -> float: ...
    def get_metadata_json(self) -> str: ...
    def set_metadata_json(self, value: str) -> None: ...
    def __str__(self) -> str: ...

class Stack:
    def __init__(self, children: Optional[list[Track]] = None) -> None: ...
    def get_name(self) -> Optional[str]: ...
    def set_name(self, value: Optional[str]) -> None: ...
    def tracks(self) -> list[Track]: ...
    def children(self) -> list[Track]: ...
    def clear_children(self) -> None: ...
    def add_track(self, track: Track, insertion_index: int = -1) -> None: ...
    def delete_track(self, id: str) -> Optional[Track]: ...
    def set_tracks(self, tracks: list[Track]) -> None: ...
    def sanitize(self) -> None: ...
    def get_track_by_id(self, id: str) -> Optional[tuple[int, Track]]: ...
    def get_item(self, id: str) -> Optional[tuple[int, int, Item]]: ...
    def delete_item(
        self,
        id: str,
        replace_with_gap: bool,
    ) -> list[tuple[int, Item]]: ...
    def insert_item_at_time(
        self,
        dest_track_index: int,
        dest_time: float,
        item: Union[Item, Clip, Gap],
        overlap_policy: OverlapPolicy,
        insert_policy: InsertPolicy,
        linked_audio_clips: Optional[list[Union[Item, Clip]]] = None,
        linked_video_clip: Optional[Union[Item, Clip]] = None,
    ) -> Optional[Union[str, dict[str, Any]]]: ...
    def get_metadata_json(self) -> str: ...
    def set_metadata_json(self, value: str) -> None: ...
    def __str__(self) -> str: ...
    def insert_item_at_index(
        self,
        dest_track_id: str,
        dest_index: int,
        item: Union[Item, Clip, Gap],
        overlap_policy: OverlapPolicy,
        linked_audio_clips: Optional[list[Union[Item, Clip]]] = None,
        linked_video_clip: Optional[Union[Item, Clip]] = None,
    ) -> Optional[Union[str, dict[str, Any]]]: ...
    def unlink_item(self, item_ids: list[str]) -> int: ...
    def link_item(self, item_ids: list[str]) -> Optional[int]: ...
    def move_item_at_time(
        self,
        item_id: str,
        dest_track_id: str,
        dest_time: float,
        replace_with_gap: bool,
        overlap_policy: OverlapPolicy,
        insert_policy: InsertPolicy,
    ) -> bool: ...
    def move_item_at_index(
        self,
        item_id: str,
        dest_track_id: str,
        dest_index: int,
        replace_with_gap: bool,
        overlap_policy: OverlapPolicy,
        insert_policy: InsertPolicy,
    ) -> bool: ...
    def split_item_at_time(self, item_id: str, split_time: float) -> bool: ...
    def resize_item(
        self,
        item_id: str,
        new_start_time: float,
        new_duration: float,
        overlap_policy: OverlapPolicy,
        clamp_to_media: bool,
    ) -> bool: ...
    def replace_item(
        self,
        item_id: str,
        item: Union[Item, Clip, Gap],
        linked_audio_clips: Optional[list[Union[Item, Clip]]] = None,
        linked_video_clip: Optional[Union[Item, Clip]] = None,
    ) -> bool: ...

class Timeline:
    def __init__(self, tracks: Optional[Union[Stack, list[Track]]] = None) -> None: ...
    @staticmethod
    def parse_json(s: str) -> Timeline: ...
    def to_json(self) -> str: ...
    def validate(self) -> list[str]: ...
    def sanitize(self) -> None: ...
    def get_name(self) -> Optional[str]: ...
    def set_name(self, value: Optional[str]) -> None: ...
    def get_stack(self) -> Stack: ...
    def set_stack(self, stack: Stack) -> None: ...
    def add_track(self, track: Track, insertion_index: int = -1) -> None: ...
    def delete_track(self, id: str) -> Optional[Track]: ...
    def move_item(self, item_id: str, dest_track_id: str, dest_time: float) -> bool: ...
    def get_metadata_json(self) -> str: ...
    def set_metadata_json(self, value: str) -> None: ...
    def __str__(self) -> str: ...
