from __future__ import annotations

from typing import List

__all__ = ["Timeline"]

class Timeline:
    def __init__(self) -> None: ...
    @staticmethod
    def parse_json(s: str) -> Timeline: ...
    def to_json(self) -> str: ...
    def validate(self) -> List[str]: ...
    def sanitize(self) -> None: ...
