name: CI

on:
  push:
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get update && sudo apt-get install -y just
      - run: just build-all
      - run: cargo test -p tellers-timeline-core -p tellers-timeline-schema -q

  python-binding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: dtolnay/rust-toolchain@stable
      - name: Set up venv and install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install maturin pytest
      - name: Build and develop Python extension
        run: |
          source .venv/bin/activate
          maturin develop -m bindings/python/Cargo.toml -q
      - name: Run Python tests
        run: |
          source .venv/bin/activate
          pytest -q bindings/python/tests

  wasm-binding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo build -p tellers-timeline-wasm --target wasm32-unknown-unknown -q

  flutter-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build -p tellers-timeline-flutter-native -q
